kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: springbootk8s-deploy
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: springbootk8s
    spec:
      containers:
      - name: springbootk8s
        image: kriscontainers.azurecr.io/ukphillips/springbootk8s:1.0.8-0d8f1b1
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: env_secret
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: springbootk8s
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: springbootk8s
